### ISSUE TITLE
Twig Runtime Error on Redirects Page

### ISSUE THREAD

**Issue by kmgdevelopment** [ethercreative/seo#134]
### Description
I get a Twig runtime error when I navigate to the "Redirects" page in the control panel:

[seo_twig_errors.txt](https://github.com/ethercreative/seo/files/2362518/seo_twig_errors.txt)

### Steps to reproduce

1. Click on "Redirects" under the SEO tab in the control panel sidebar.

### Additional info

- Craft version: 3.0.23.1
- SEO version: 3.4.1
- PHP version: 7.1.12
- Database driver & version: mysql 5.6.38
- Other Plugins: Amazon S3, Redactor

**Comment by Tam** [comment]
Fixed in [v3.4.3](https://github.com/ethercreative/seo/releases/tag/v3.4.3)

**Comment by ryanmasuga** [comment]
I've updated my local version of this plugin to 3.4.4 and I'm definitely still seeing the Twig error on this settings page.

### Additional info

- Craft version: 3.0.23.1
- SEO version: 3.4.4
- PHP version: 7.0.30

Pic of the error (which shows the error occurring on the same line that was altered in 8ce5def): http://cloud.gomasuga.com/742e9ebf5345

**Comment by Tam** [comment]
@ryanmasuga Can you try clearing your compiled template caches to see if the issue persists (you might need to manually delete the compiled templates for the control panel)?

**Comment by ryanmasuga** [comment]
That did the trick - I should have thought of that. Thanks, @Tam!
